name: Docker Image CI

on:
  schedule:
    - cron: 0 1 * * 3 # every wednesday at 1 AM
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
      
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Build and Push container to ACR
      run: |
        echo "Used cloudprober version: ${{ vars.CLOUDPROBERVERSION }}"
        docker build -t conplementag/win-cloudprober:latest-2022 --build-arg CLOUDPROBERVERSION=${{ vars.CLOUDPROBERVERSION }} .
        docker push conplementag/win-cloudprober:latest-2022

