name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
      
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Build and Push container to ACR
      run: |
        docker build -t conplementag/win-cloudprober:latest-2022 .
        docker push conplementag/win-cloudprober:latest-2022

